# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ractive.jsでまなぶSPA
email: info@mokelab.com
description: > # this means to ignore newlines until "baseurl:"
  Ractive.jsを使ってSPA(Single Page Application)の作り方をまなぶための教科書です。

baseurl: "/ractivejs-spa-textbook" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mokelab
github_username:  mokelab

# Build settings
markdown: kramdown
